language: python
dist: trusty
services:
  - docker
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database stoic_test;' -U postgres
python:
  - "3.5"
cache: pip
install:
  - "pip install -r dev-requirements.txt"
  - "pip install -r requirements.txt"
  - "python setup.py develop"
script: 
  - FLASK_CONFIG=testing py.test --pep8 images 
  - FLASK_CONFIG=testing py.test -v --cov=images --cov-report term-missing --pep8 test
after_success:
  - coveralls
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t kolbman.xyz:3333/images .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $DOCKER_REGISTRY;
    docker push kolbman.xyz:3333/images;
    fi
